version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  udoc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udoc
    stdin_open: true
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
